---

imagePullSecrets:
  - name: dr-simbirsoft1-com-ext-projects

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: polyn-tech-demo.ci.simbirsoft.dev
      paths:
        - path: /
          pathType: Prefix

networkPolicy:
  enabled: true
  spec:
    podSelector:
      matchLabels:
        app.kubernetes.io/instance: polynfront
    policyTypes:
      - Ingress
      - Egress
    ingress:
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: ingress-nginx
            podSelector:
              matchLabels:
                app.kubernetes.io/name: ingress-nginx
        ports:
          - port: 80
            protocol: TCP
    egress:
      - to:
          - namespaceSelector: {}
        ports:
          - port: 53
            protocol: TCP
          - port: 53
            protocol: UDP

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 80

livenessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

startupProbe:
  httpGet:
    path: /healthz
    port: http
  failureThreshold: 30
  periodSeconds: 10
