<template>
  <div>
    <b-form-group id="fieldset-1" :label="label" :invalid-feedback="invalidData" :state="!isError" style="position: relative">
      <h5 :class="{ 'upload-title': isInference }">
        {{ isInference ? 'Validation (optional field)' : '' }}

        <b-question-fill
          v-if="isInference"
          style="transform: scale(0.7); position: absolute; right: -20px; top: 2px"
          :id="isInference ? 'inference-tooltip' : 'fileupload-tooltip'"
        />
        <b-tooltip :target="isInference ? 'inference-tooltip' : 'fileupload-tooltip'" triggers="hover" placement="right">
          {{
            isInference
              ? 'The "Validation" field is used to validate data that has not been in classifier training. It is allowed to upload one file containing at least 24000 samples and up to 150 Mb in size. '
              : 'VibroSense neural core (encoder) is trained to extract features from vibration signal generated by various accelerometer sensors. The output is presented as embeddings.'
          }}
        </b-tooltip>
      </h5>

      <b-form-file
        v-model="value"
        accept=".csv"
        :multiple="isInference ? false : true"
        placeholder="*Drag and drop your .csv dataset file or"
        :class="{ 'field-error': !isValid }"
        browse-text="Browse"
        :file-name-formatter="formatNames"
        :disabled="isDisabled"
      />
    </b-form-group>
  </div>
</template>

<script lang="ts" src="./p-upload-file.component.ts" />
<style scoped lang="scss" src="./p-upload-file.scss" />
