<template>
  <div class="overlay" v-if="onRun">
    <div class="overlay__text" v-if="onRun">
      <div style="width: 350px">
        <p class="overlay__text__bold">{{ isProcessing }}</p>
      </div>
    </div>
  </div>

  <div class="simulation-page" style="transform: scale(0.9)">
    <section class="simulation-page__section _left">
      <div v-if="!isRenameActive" class="header">
        <h1 class="header__title">{{ header }}</h1>
        <b-pencil-square font-scale="2" class="icon" @click="renameHeader" style="fill: #47525e" />
        <!-- <i class="icon icon_large icon-rename" @click="renameHeader" /> -->
      </div>
      <b-form-input v-else v-model.trim="header" class="input" @keyup.enter="submitNewName" @blur="submitNewName" />

      <p v-if="type === 'Clustering'" class="info">Select your data files and choose clustering algorithm.</p>
      <p v-else class="info">
        Select your data files and choose classification method. Each uploaded file will be recognized later as a separate class.
      </p>
      <p v-if="type === 'Classification'" class="info">
        <span class="info__bold">IMPORTANT!</span> Each data file will be recognised later as separate class.
      </p>

      <div style="display: grid; grid-template-columns: 1fr 1fr; grid-template-rows: repeat(1fr 1fr 1fr); gap: 30px 50px">
        <div class="simulation-page__section__form_position">
          <p-upload-file v-model="dataFile" :dataFile="dataFile" />
        </div>
        <div v-if="type !== 'Clustering'">
          <p-upload-file
            :class="{ available: dataFile }"
            v-model="inferenceFile"
            :dataFile="inferenceFile"
            :isInference="true"
            :isDisabled="isButtonDisabled"
            style="opacity: 0.5; width: 500px; margin-top: 8px"
          />
        </div>
        <div v-if="type === 'Clustering'" />
        <div class="simulation-page__section__form_position">
          <img src="../../../content/image/vibroSense_chip.svg" alt="prompt" class="vibrosense__svg" />
          <div class="static-chip">
            <div style="position: relative">
              <p style="color: #47525e; margin-bottom: 0; font-weight: 700">NASP Vibrosense encoder core</p>
              <b-question-fill
                style="transform: scale(0.7); position: absolute; right: -20px; top: 5px; fill: #333"
                :id="'vibrosense-encoder'"
              />
              <b-tooltip target="vibrosense-encoder" triggers="hover" placement="right" class="qwe">
                VibroSense neural core (encoder) is trained to extract features from vibration signal generated by various accelerometer
                sensors. The output is presented as embeddings.
              </b-tooltip>
            </div>
          </div>
        </div>

        <div />
        <!-- <p-upload-file v-model="inferenceFile" label="Algorithm:" /> -->
        <div :class="{ customfilelabel: true, available: dataFile }">
          <img src="../../../content/image/algorithm.svg" alt="prompt" class="algorithm__img" />
          <div class="simulation-page__section__form__algorithm-wrapper">
            <h5 class="algorithm-subtitle">
              {{ type === 'Clustering' ? 'Choose algorithm' : 'Choose method' }}
              <b-question-fill class="question__icon" style="right: -2px; top: -1px" id="tooltip-target-1" />
              <b-tooltip target="tooltip-target-1" triggers="hover" placement="right" class="qwe">{{ tooltip }}</b-tooltip>
            </h5>
            <div style="width: 400px">
              <multiselect
                v-if="multiselectOptions"
                v-model="multiselectValue"
                :options="multiselectOptions"
                :close-on-select="true"
                label="name"
                track-by="name"
                :preselect-first="true"
                placeholder="Choose"
                :searchable="false"
                :allow-empty="false"
                deselect-label="Can't remove this value"
                :disabled="isButtonDisabled"
                open-direction="bottom"
                maxHeight="300px"
              />
            </div>
          </div>
        </div>

        <!-- Линии соединяющие блоки -->
        <div style="position: absolute">
          <hr
            :class="{ 'bold-line': dataFile }"
            style="position: absolute; height: 46px; top: 91px; left: 289px; border-right: 4px solid #bdbbbb"
          />
          <hr
            :class="{ 'bold-line': dataFile }"
            style="position: absolute; height: 45px; top: 237px; left: 290px; border-right: 3px solid #bdbbbb"
          />
          <div v-if="type === 'Classification'">
            <hr
              :class="{ solid_bold: inferenceFile, 'bold-line': inferenceFile }"
              style="position: absolute; width: 300px; top: 170px; left: 566px; border-top: 4px dashed #bdbbbb"
            />
            <hr
              :class="{ solid_bold: inferenceFile, 'bold-line': inferenceFile }"
              style="position: absolute; height: 78px; top: 92px; left: 866px; border-right: 4px dashed #bdbbbb"
            />
            <hr
              :class="{ solid: inferenceFile, 'bold-line': inferenceFile }"
              style="position: absolute; width: 300px; top: 205px; left: 566px; border-top: 3px dashed #bdbbbb"
            />
            <hr
              :class="{ solid: inferenceFile, 'bold-line': inferenceFile }"
              style="position: absolute; height: 78px; top: 205px; left: 866px; border-right: 3px dashed #bdbbbb"
            />

            <hr
              :class="{ 'bold-line': inferenceFile }"
              style="position: absolute; width: 47px; top: 330px; left: 565px; border-top: 3px solid #bdbbbb"
            />
          </div>
          <div :class="{ 'arrow-bold': inferenceFile }" v-if="type === 'Classification'" class="arrow" />
        </div>

        <div v-if="type === 'Classification'" class="simulation-page__section__form_position">
          <div :class="{ 'static-trained': true, 'static-trained__active': dataFile }">
            <div style="position: relative">
              <p style="color: #47525e; margin-bottom: 0; font-weight: 700">Trained classifier</p>
            </div>
          </div>
        </div>
      </div>

      <div v-if="checkDatafileAndType()" class="options-block">
        <div class="options-block__proportion">
          <div class="proportion-label">
            Train/Test proportion:
            <b-question-fill class="question__icon" id="proportion" />
            <b-tooltip target="proportion" triggers="hover" placement="right"
              >Set the ratio of data going into the classifier training and into the test.</b-tooltip
            >
          </div>
          <div class="proportion-inputs">
            <b-form-input
              v-model="proportion"
              type="range"
              min="0"
              max="1"
              step="0.01"
              class="proportion-inputs__range"
              :disabled="fieldDisabledToggle.proportion"
            />
            <b-form-input v-model="proportion" class="proportion-inputs__number" :disabled="fieldDisabledToggle.proportion" />
          </div>
        </div>
        <div class="splitter__wrapper">
          <h5 class="algorithm-subtitle" style="text-align: left; left: 10px">
            Splitter type:
            <b-question-fill class="question__icon" id="splitter" />
            <b-tooltip target="splitter" triggers="hover" placement="right"
              >Select the method of data sampling for training the classifier.</b-tooltip
            >
          </h5>
          <div>
            <multiselect
              v-model="selectedSplitterType"
              :options="splitterType"
              :close-on-select="true"
              label="name"
              track-by="name"
              :preselect-first="true"
              placeholder="Choose"
              :searchable="false"
              :allow-empty="false"
              deselect-label="Can't remove this value"
              :disabled="isButtonDisabled"
              :inf="true"
              maxHeight="260px"
              class="multiselect_splitter"
            />
          </div>
        </div>
      </div>

      <div class="buttons-group">
        <p-button class="simulation-page__btn _secondary" @click="redirectBack">Back</p-button>
        <b-overlay :show="onRun" rounded opacity="0.6" spinner-type="null">
          <p-button class="simulation-page__btn _primary" @click="runSimulation" :disabled="isButtonDisabled"> Run Simulation </p-button>
        </b-overlay>
      </div>
      <div class="info simulation-page__section__form__prompt">
        *Data is not stored on our servers and used only for the current session
      </div>
    </section>
  </div>
</template>

<style src="vue-multiselect/dist/vue-multiselect.min.css"></style>

<script lang="ts" src="./create.component.ts" />

<style scoped lang="scss" src="./create.scss" />
