{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simbirsoft-universal-chart.fullname" . }}
  labels:
    {{- include "simbirsoft-universal-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.extraPorts }}
    {{- include "helpers.common.tplvalues.render" (dict "value" .Values.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector:
    {{- include "simbirsoft-universal-chart.selectorLabels" . | nindent 4 }}
{{- end }}
